version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14
      docker: 19
    commands:
      - echo Installing dependencies...
      - npm install
      - echo Installing kubectl...
      - curl -LO "https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl"
      - chmod +x ./kubectl
      - mv ./kubectl /usr/local/bin/kubectl
      - echo Installing jq...
      - yum install -y jq

  pre_build:
    commands:
      - echo Retrieving DockerHub credentials from AWS Secrets Manager...
      - export DOCKERHUB_CREDS=$(aws secretsmanager get-secret-value --secret-id arn:aws:secretsmanager:us-east-1:654654291247:secret:dockerhubcreds-KM1jTu --query 'SecretString' --output text)
      - export DOCKERHUB_USERNAME=$(echo $DOCKERHUB_CREDS | jq -r .username)
      - export DOCKERHUB_PASSWORD=$(echo $DOCKERHUB_CREDS | jq -r .password)
      - echo Logging in to DockerHub...
      - echo $DOCKERHUB_PASSWORD | docker login -u $DOCKERHUB_USERNAME --password-stdin
      - echo Configuring kubectl...
      - aws eks update-kubeconfig --name Tetris-EKS-Cluster --region us-east-1 --role-arn arn:aws:iam::654654291247:role/your-codebuild-role

  build:
    commands:
      - echo Build started on `date`
      - echo "Listing current directory contents:"
      - ls -alh  # List files to check the directory structure
      - echo "Changing to frontend directory..."
      - cd frontend  # Change to the frontend directory
      - npm run build
      - echo Building Docker image...
      - docker build -t foxe03/messaging-app-frontend .
      - echo Pushing Docker image...
      - docker push foxe03/messaging-app-frontend

  post_build:
    commands:
      - echo Updating Kubernetes deployment...
      - kubectl set image deployment/messaging-app-frontend messaging-app-frontend=foxe03/messaging-app-frontend:$CODEBUILD_RESOLVED_SOURCE_VERSION

artifacts:
  files:
    - '**/*'
  discard-paths: yes
